export enum DialogType {
	AccountConfirmationDialog = 'account-confirmation-dialog',
	AccountDialog = 'account-dialog',
	AccountTokenValidateDialog = 'account-token-validate-dialog',
	AccountVerificationCodeDialog = 'account-verification-code-dialog',
	AlertInfoDialog = 'alert-info-dialog',
	CheckServerConnectionDialogName = 'check-server-connection-dialog',
	DirectoryBrowserDialog = 'directory-browser-dialog',
	DownloadDetailsDialog = 'download-details-dialog',
	HelpInfoDialog = 'help-info-dialog',
	MediaDownloadConfirmationDialog = 'media-download-confirmation-dialog',
	MediaSelectionDialog = 'media-selection-dialog',
	ResetDatabaseConfirmationDialog = 'reset-database-confirmation-dialog',
	ServerHideConfirmationDialog = 'server-hide-confirmation-dialog',
	ServerSettingsDialog = 'server-settings-dialog',
	SetupSkipConfirmationDialog = 'setup-skip-confirmation-dialog',
}
