name: Build multiarch docker containers

on:
  workflow_dispatch:
  push:
    branches:
      - multiarch
      - test/**
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '.run/**'
      - '.vscode/**'
      - '.releaserc.json'

jobs:
  # Build And Release Docker Image
  CreateDockerImagesMutliarch:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish to Registry with dev tag
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
        with:
          name: frosit/plexripper
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: VERSION
          tags: "multiarch"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
