name: Create PlexRipper Dev Container Release

on:
    workflow_dispatch:
    push:
        branches:
            - dev
        paths-ignore:
            - '.github/**'
            - '.idea/**'
            - '.run/**'
            - '.vscode/**'
            - '.releaserc.json'

jobs:
    # Build And Release Docker Image
    build-and-publish:
        name: Build and Publish On Dev Tagged Docker Image
        runs-on: self-hosted
        steps:
            -   name: Checkout source code
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_TOKEN }}
                    fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

            -   name: Get latest version tag
                id: version
                uses: WyriHaximus/github-action-get-previous-tag@v1

            -   name: Echo last version tag
                run: echo ${{ steps.version.outputs.tag }}

            - name: Strip 'v' from version
              id: strip_v
              run: |
                  # Strip the 'v' prefix from the version tag
                  VERSION_NO_V="${{ steps.version.outputs.tag }}"
                  VERSION_NO_V="${VERSION_NO_V#v}"
                  echo "VERSION_NO_V=$VERSION_NO_V" >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              env:
                  VERSION: ${{ env.VERSION_NO_V }}
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: frosit/plexripper:dev
                  build-args: VERSION
                  file: docker/Dockerfile
