name: Publish Docker latest and version tagged image
# This should only run when a release is created with a version tag
on:
  workflow_dispatch:
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '.run/**'
      - '.vscode/**'
      - '.releaserc.json'

jobs:
  call-workflow-semantic-release:
    uses: ./.github/workflows/semantic-release-part.yml
    secrets: inherit
  # Build Docker Image
  CreateDockerLatestAndTagRelease:
    needs: [ call-workflow-semantic-release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: Get latest version tag
        id: version
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          prefix: v
      - name: Stable tag_name
        run: echo ${{ github.event.release.tag_name }}
      - name: Publish to Docker with latest and version tag
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: frosit/plexripper
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.version.outputs.tag }}"
