name: Qodana Scan
on:
    workflow_dispatch:
#    push:
#        branches:
#            - dev

jobs:
    qodana:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: 'Qodana Scan'
                uses: JetBrains/qodana-action@v2024.1
                with:
                    pr-mode: false
                    post-pr-comment: false
                    args: --property, qodana.net.solution=PlexRipper.sln
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
                    QODANA_ENDPOINT: 'https://qodana.cloud'
